### PR TITLE
Return user's first-name with message

### PR DESCRIPTION
**Pull request by Nzbuu**
Supports a more personal bot experience.

### CODE REVIEW

**Comment by rusboard** [comment]
Hi, did you test it before commit? Because example not compiling :)

There is a error:
```
error: 'message' was not declared in this scope
String from_name = message.from_name;
```

Need change
`String from_name = message.from_name;`
to
`String from_name = bot.messages[i].from_name;`

**Comment by Nzbuu** [comment]
Yes, sorry. Looks like I've introduced an error in the examples as you say. But the library code is definitely OK since I have a device using it right now.

**Comment by rusboard** [comment]
Yes, library code OK. Example not. 
Will you commit fix?

**Comment by witnessmenow** [comment]
Easy mistake to make, I've often broke the examples!

Created #18 for this

**Pull request merged**
