### PR TITLE
Edit message

### PR DESCRIPTION
**Pull request by RomeHein**
Hi, 
I really like your library, I needed a way to reload the state of my inline keyboard (showing a list of gpio states) without having to generate a new menu. 
So I've updated only the part I needed of your library. I think it's fine because the use case behind editMessageText is mainly for updating inline keyboard. 
⚠️⚠️⚠️
- this is my first ever pull-request 😱
- I've never ever done any c++ 😱😱😱
So don't hesitate to correct me.
Thanks again for your amazing work!

### CODE REVIEW

**Comment by didgerihorn** [comment]
This would be quiete useful, since the message id is also required if you want to reply to a message

**Comment by RomeHein** [comment]
@witnessmenow is there a process to respect or do you have any advices to push things forward? I think this feature could be nice, and I believe it was the subject of an issue 🙂It's really nice to be able to update a message containing buttons, without having to replace it or send a new one.

**Comment by witnessmenow** [comment]
I will be releasing a new version in the next few weeks. I won't be
developing any new features for it, but if there is a working pull request
with this feature I think it would be good to include

**Comment by fritsjan** [comment]
I used this pull-request as a guide for the same thing I wanted to do. I made a fully mergable working pull-request see: #190 . It also has a working example and some other bug-fixes.

**Comment by witnessmenow** [comment]
Thank you for the PR @RomeHein , I'm really sorry how long it has taken me to get to these.

Your work has been incorporated into #203 and is currently awaiting PR.

I have opened #204 as well, an issue just to add a simple edit message example as well as the edit keyboard example that is in #203

**Pull request closed without merging**
